name: Continuous Integration - Protocol

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'protocol/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Protocol Tests
        uses: actions/setup-node@v1
        with:
          node-version: '16'
      - name: Cache Node Modules
        id: node-modules-cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install Dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: yarn install --immutable
      - run: yarn generate
        working-directory: protocol
      - run: yarn test
        working-directory: protocol
